### ISSUE TITLE
Recreated interface

### ISSUE THREAD

**Issue by nyzd** [DeployContract/dc-frontend#3]
We created this before in the library package

```typescript
import { NavigationItem } from "library";
```

https://github.com/ContractSupplyChain/csc-frontend/blob/79efa85f9f705d93d0d672aefa49ea753368ca91/src/sections/intro/web/Header.tsx#L35

Example for NavigationItem:
```typescript 
Array<NavigationItem<ReactElement<typeof Icon>>>
```

**Comment by al-abd** [comment]
I was waiting for the library to be completed, the problem will be fixed.

**Comment by nexnema** [comment]
Check out code, if there is no other problem please close Issue.

[https://github.com/ContractSupplyChain/csc-frontend/commit/61a26704b18fe7c846a4f0404eb10038deb7ba2d](url)

**Comment by al-abd** [comment]
Check out code, if there is no other problem please close Issue.

[https://github.com/ContractSupplyChain/csc-frontend/commit/61a26704b18fe7c846a4f0404eb10038deb7ba2d](url)
